### ISSUE TITLE
Typed array or buffer input

### ISSUE THREAD

**Issue by creationix** [clark800/bigint-base-converter#3]
It would be nice if this accepted typed arrays and buffers as input.  Then I could do something like:

```js
const BASE36 = '0123456789abcdefghijklmnopqrstuvwxyz'
let buf = require('crypto').randomBytes(32)
console.log(buf, 256, BASE36))
```

To convert a node buffer into it's base36 string value.  It currently works if I first convert the typed array to a normal array using `[].slice.call(buf)`, but it would be less overhead if your code simply allowed working with typed arrays (as long as the base never went above the typed array's limit)

**Comment by clark800** [comment]
I consider type introspection to be an anti-pattern; I'd suggest using a wrapper function to do the conversion.
